run:
  timeout: 5m
  tests: true

output:
  sort-results: true

linters:
  enable:
    - depguard
    - gofumpt
    - goimports
    - revive
    - misspell
    - promlinter
    - tenv
    - errorlint
    - errname
    - predeclared
    - contextcheck
    - exhaustive
    - gocritic
    - importas
    - nakedret
    - prealloc
    - unconvert
    - testifylint
    - godot
    - copyloopvar

issues:
  max-same-issues: 0

linters-settings:
  depguard:
    rules:
      test:
        files:
          - "$test"
        deny:
          - pkg: "github.com/stretchr/testify/assert"
            desc: "Use github.com/stretchr/testify/require instead of github.com/stretchr/testify/assert"
          - pkg: "io/ioutil"
            desc: "Use corresponding 'os' or 'io' functions instead."
  goimports:
    local-prefixes: github.com/cloudflare/pint
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
  nakedret:
    max-func-lines: 0
