name: Compile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2

      - name: Cache Go modules and build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ env.GITHUB_REF_SLUG }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-main-go-

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          args: build -p 2 --snapshot --rm-dist
